# Database Connection
connectionURL = jdbc:mysql://localhost:3306/imdb
user = root
password = 
driver = com.mysql.cj.jdbc.Driver

# Mapping and Output
mappingFile = audiovisual_mappings.ttl
outputFile = out.ttl
format = TURTLE